---
driver:
  flavor_ref: 'm1.medium'

suites:
  - name: default
    run_list:
      - recipe[osl-letsencrypt-boulder-server]
      - recipe[boulder_test]
    excludes:
      - centos-6
    attributes:
      boulder:
        host_aliases:
          - foo.org
