---
driver:
  flavor_ref: 'm1.medium'
  attributes:
    yum:
      epel:
        baseurl: http://epel.osuosl.org/7/$basearch
        gpgkey: http://epel.osuosl.org/RPM-GPG-KEY-EPEL-7

suites:
  - name: default
    run_list:
      - recipe[osl-letsencrypt-boulder-server]
      - recipe[boulder_test]
    attributes:
      boulder:
        host_aliases:
          - foo.org
verifier:
  name: inspec
